version: "3"
services:
  as:
    build: .
    ports:
      - "3000:3000"
    restart: unless-stopped
    links:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo/data:/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
    ports:
      - "27017:27017"
