#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'
services:
  as:
    build: ./as
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongo-as:27017/xyzdb?authSource=admin
      - MONGO_USERNAME=docker
      - MONGO_PASSWORD=docker
      - DEBUG
    links:
      - mongo-as
    depends_on:
      - mongo-as
  client-api:
    build: ./client/api
    ports:
      - '3001:3001'
    environment:
      - MONGO_URL=mongodb://mongo-client:27017/xyzdb?authSource=admin
      - MONGO_USERNAME=docker
      - MONGO_PASSWORD=docker
      - DEBUG
    links:
      - mongo-client
    depends_on:
      - mongo-client
  mongo-as:
    image: mongo:latest
    volumes:
      - ./mongo/as/data:/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
  mongo-client:
    image: mongo:latest
    volumes:
      - ./mongo/client/data:/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
  web:
    build: ./client/web
    ports:
      - '5000:5000'
    links:
      - client-api
    depends_on:
      - client-api
    environment:
      - DEBUG
